config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root to: 'homes#top'
# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do
  root 'homes#top'
  resources :items, only: [:index, :new, :create, :show, :edit, :update]
  resources :genres, only: [:index, :create, :edit, :update,]
  resources :customers, only: [:index, :show, :edit, :update]
  resources :orders, only: [:show, :update]
  resources :order_details, only: [:update]
  # resource :genres, only: [:create, :edit]
end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  scope module: :public do
    root to: 'homes#top'
    get '/homes/about' => "homes#about"
    resources :items, only: [:index, :show]
    get'/customers/information'=>'customers#show'
    get'/customers/information/edit'=>'customers#edit'
    patch'/customers/information'=>'customers#update'
    get'/customers/check'=>'customers#check'
    patch'/customers/withdraw'=>'customers#withdraw'
    get '/customers/check'=>'customers#check'
    patch '/customers/withdraw'=>'customers#withdraw'
    #post '/items' => 'items#create'
    delete '/cart_items' => 'cart_items#all_destroy', as: 'all_destroy'
    patch 'cart_items' => 'cart_items#create'
    resources :cart_items, only:[:index, :update, :create, :destroy]
    resources :orders, only:[:new, :index, :show]
    post '/orders/confirm'=>'orders#confirm'
    get '/orders/thanks'=>'orders#thanks'
    post '/orders/complete'=>'orders#complete'
    resources :addresses, only:[:index, :edit, :create, :update, :destroy]
    resources :genres, only: [:show], as: "customers_genres", path: "customers/genres"
  end


end

app/models/address.rb
class Address < ApplicationRecord
 belongs_to :customer
 
  def zip_code_and_address_and_name
    "〒#{self.zip_code}  #{self.address}  #{self.name}"
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :cart_items
  has_many :orders

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :addresses
         
  def active_for_authentication?
    super && self.is_active?
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
 has_one_attached :image

 belongs_to :genre

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  enum status: { 入金待ち: 0, 入金確認: 1, 製作中:2, 発送準備中:3, 発送済み:4 }
  enum payment_method: { クレジットカード: 0, 銀行振込: 1 }
  # 入金待ち="0"、入金確認="1"、製作中="2"、発送準備中="3"、発送済み="4"

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  enum creating_status: {
      "着手不可" => 0,
      "製作待ち" => 1,
      "製作中" => 2,
      "製作完了" =>3,
  }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to '/admin/customers'
  end

  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :address, :zip_code, :phone_number, :email, :is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 #before_action :configure_permitted_parameters, if: :devise_controller?
before_action :authenticate_admin!, if: :admin_url
before_action :authenticate_customer!, if: :customer_url

   private
   def admin_url
     request.fullpath.starts_with?('/admin')
   end
   
   def customer_url
     request.fullpath.starts_with?('/cart_items')
   end

   def after_sign_in_path_for(resource)
     case resource
     when Admin
         admin_root_path
     when Customer
         root_path
     end
   end
   
  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :admin
       new_admin_session_path
    elsif resource_or_scope == :customer
       root_path
    end
  end

#   private
#   def configure_permitted_parameters
#     devise_parameter_sanitizer.permit(:sign_in, keys:[:email, :encrypted_password])
#     devise_parameter_sanitizer.permit(:sign_up, keys:[:email, :phone_number, :zip_code, :address, :first_name_kana, :last_name_kana, :first_name, :last_name])
#     devise_parameter_sanitizer.permit(:account_update, keys:[:email, :phone_number, :zip_code, :address, :first_name_kana, :last_name_kana, :first_name, :last_name])
#   end

 end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/admin_helper.rb
module Admin::AdminHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/admin/customers/edit.html.erb
<div class="container px-5 px-sm-0">
<h2><%= (@customer.last_name + @customer.first_name) %>さんの会員情報編集</h2>
  <div class="row mt-4">
<%= form_with model: @customer,url: admin_customer_path, method: :patch do |f| %>
<table class="table table-borderless">
            <thead>
              <tr>
                <td>会員ID</td>
                <td><%= @customer.id %></td>
                <%= f.label :"#{@customer.id}" %>
              </tr>
              <tr>
                <td>氏名</td>
                <td><%= f.text_field :last_name %></td>
                <td><%= f.text_field :first_name %></td>
              </tr>
              <tr>
                <td>フリガナ</td>
                <td><%= f.text_field :last_name_kana %></td>
                <td><%= f.text_field :first_name_kana %></td>
              </tr>
              <tr>
                <td>郵便番号</td>
                <td><%= f.text_field :zip_code %></td>
              </tr>
              <tr>
                <td>住所</td>
                <td><%= f.text_field :address %></td>
              <tr>
              <tr>
                <td>電話番号</td>
                <td><%= f.text_field :phone_number %></td>
              </tr>
              <tr>
                <td>メールアドレス</td>
                <td><%= f.text_field :email %></td>
              </tr>
              <tr>
                <td>会員ステータス</td>
                <td><%= f.radio_button :is_active, value: true %>有効</td>
                <td><%= f.radio_button :is_active, value: false %>退会</td>
                <tr/>
                <tr>
                  <td></td>
                <td><%= f.submit '変更を保存', class:'btn btn-success' %></td>
              </tr>
            </thead>
          </table>
<% end %>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row my-5">
      
      <h2>会員一覧</h2>
      
  </div>
  <div class="row my-3">
    <div class="col-sm-12 offset-sm-1">
      <table class="table thead-light">
        
        <thead>
          <tr>
            <th class="table-secondary">会員ID</th>
            <th class="table-secondary">氏名</th>
            <th class="table-secondary">メールアドレス</th>
            <th class="table-secondary">ステータス</th>
          </tr>
        </thead>
        
        <tbody>
          <% @customers.each do |customer| %>
            <tr>
              <td class="align-middle"><%= customer.id %></td>
              <td class="align-middle"><u><%= link_to customer.last_name + customer.first_name, admin_customer_path(customer.id), class:"font-weight-bold" %></u></td>
              <td class="align-middle"><%= customer.email %></td>
              <td class="align-middle">
                <% if customer.is_active == true %>
                  <p class="text-success font-weight-bold">有効</p>
                <% else %>
                  <p>退会</p>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
        
      </table>
      <%= paginate @customers %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row my-3">
    <div class="col-sm-8 offset-sm-1">
      <h2><%= @customer.last_name + @customer.first_name %>さんの会員詳細</h2>
    </div>
  </div>
  
  <div class="row">
    <div class="col-sm-6 offset-sm-1">
      <table class="table ">
        <tr>
          <th class=>会員ID</th>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <th class=>氏名</th>
          <td><%= @customer.last_name + @customer.first_name %></td>
        </tr>
        <tr>
          <th class=>フリガナ</th>
          <td><%= @customer.last_name_kana + @customer.first_name_kana %></td>
        </tr>
        <tr>
          <th class=>郵便番号</th>
          <td><%= @customer.zip_code %></td>
        </tr>
        <tr>
          <th class=>住所</th>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <th class=>電話番号</th>
          <td><%= @customer.phone_number %></td>
        </tr>
        <tr>
          <th class=>メールアドレス</th>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <th class=>会員ステータス</th>
            <% if @customer.is_active == true %>
              <td class="text-success font-weight-bold">有効</td>
            <% else %>
              <td>退会</td>
            <% end %>
        </tr>
      </table>
    </div>
  </div>
  
  <div class="row mb-2 ">
    <div class="col-lg-12 offset-sm-2">
      <%= link_to "　　編集する　　", edit_admin_customer_path(id: @customer.id), class: "btn btn-success mx-3" %>
      <%= link_to "注文履歴一覧を見る", admin_order_path(id: @customer), class: "btn btn-primary mx-3" %>
    </div>
  </div>

</div>