config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root to: 'homes#top'
# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do
  root 'homes#top'
  resources :items, only: [:index, :new, :create, :show, :edit, :update]
  resources :genres, only: [:index, :create, :edit, :update,]
  resources :customers, only: [:index, :show, :edit, :update]
  resources :orders, only: [:show, :update]
  resources :order_details, only: [:update]
  # resource :genres, only: [:create, :edit]
end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  scope module: :public do
    root to: 'homes#top'
    get '/homes/about' => "homes#about"
    resources :items, only: [:index, :show]
    get'/customers/information'=>'customers#show'
    get'/customers/information/edit'=>'customers#edit'
    patch'/customers/information'=>'customers#update'
    get'/customers/check'=>'customers#check'
    patch'/customers/withdraw'=>'customers#withdraw'
    get '/customers/check'=>'customers#check'
    patch '/customers/withdraw'=>'customers#withdraw'
    #post '/items' => 'items#create'
    delete '/cart_items' => 'cart_items#all_destroy', as: 'all_destroy'
    patch 'cart_items' => 'cart_items#create'
    resources :cart_items, only:[:index, :update, :create, :destroy]
    resources :orders, only:[:new, :index, :show]
    post '/orders/confirm'=>'orders#confirm'
    get '/orders/thanks'=>'orders#thanks'
    post '/orders/complete'=>'orders#complete'
    resources :addresses, only:[:index, :edit, :create, :update, :destroy]
    resources :genres, only: [:show], as: "customers_genres", path: "customers/genres"
  end


end

app/models/address.rb
class Address < ApplicationRecord
 belongs_to :customer
 
  def zip_code_and_address_and_name
    "〒#{self.zip_code}  #{self.address}  #{self.name}"
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :cart_items
  has_many :orders

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :addresses
         
  def active_for_authentication?
    super && self.is_active?
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
 has_one_attached :image

 belongs_to :genre

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  enum status: { 入金待ち: 0, 入金確認: 1, 製作中:2, 発送準備中:3, 発送済み:4 }
  enum payment_method: { クレジットカード: 0, 銀行振込: 1 }
  # 入金待ち="0"、入金確認="1"、製作中="2"、発送準備中="3"、発送済み="4"

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  enum creating_status: {
      "着手不可" => 0,
      "製作待ち" => 1,
      "製作中" => 2,
      "製作完了" =>3,
  }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

def index
 @orders = Order.all
end

def show
 @order = Order.find(params[:id])
 @order_items = @order.order_details
end

def thanks
end

def update
  order = Order.find(params[:id])
  order.update(order_params)
  order = Order.find(params[:id])
  # 注文ステータス[入金確認]=>制作ステータス[製作待ち]
  if order.status == "入金確認"
   order.order_details.each do |order_detail|
    order_detail.update(creating_status: "製作待ち")
   end
  redirect_to admin_order_path
end
end

def order_params
 params.require(:order).permit(:status)
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 #before_action :configure_permitted_parameters, if: :devise_controller?
before_action :authenticate_admin!, if: :admin_url
before_action :authenticate_customer!, if: :customer_url

   private
   def admin_url
     request.fullpath.starts_with?('/admin')
   end
   
   def customer_url
     request.fullpath.starts_with?('/cart_items')
   end

   def after_sign_in_path_for(resource)
     case resource
     when Admin
         admin_root_path
     when Customer
         root_path
     end
   end
   
  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :admin
       new_admin_session_path
    elsif resource_or_scope == :customer
       root_path
    end
  end

#   private
#   def configure_permitted_parameters
#     devise_parameter_sanitizer.permit(:sign_in, keys:[:email, :encrypted_password])
#     devise_parameter_sanitizer.permit(:sign_up, keys:[:email, :phone_number, :zip_code, :address, :first_name_kana, :last_name_kana, :first_name, :last_name])
#     devise_parameter_sanitizer.permit(:account_update, keys:[:email, :phone_number, :zip_code, :address, :first_name_kana, :last_name_kana, :first_name, :last_name])
#   end

 end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/admin_helper.rb
module Admin::AdminHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/admin/orders/index.html.erb
注文履歴一覧
<table class="table">
  <thead>
    <tr>
      <th scope="col">購入日時</th>
      <th scope="col">購入者</th>
      <th scope="col">注文個数</th>
      <th scope="col">注文ステータス</th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
      <td><%= link_to admin_order_path(order) do %><%= order.created_at.to_s(:datetime_jp) %><% end %></td>
      <td><%= order.customer.last_name %><%= order.customer.first_name %></td>
      <td><%= order.order_details.sum(:amount) %></td>
      <td><%= order.status %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @orders %>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="col-md-12 mx-auto mt-5">
   <div>
<div class="row mb-3">
   <h4>注文詳細</h4>
 </div>
</div>


  <div class="col-md-10 d-flex justify-content-center mt-5">
  <table class="table table-borderless">
    <thead>
      <tr>
        <th scope="col" style="width: 30%"></th>
        <th scope="col" style="width: 55%"></th>
        <th scope="col" style="width: 15%"></th>
      </tr>
    <thead>
    <tbody>
    <tr>
      <td>購入者</td>
      <td>
        <%= link_to admin_customer_path(@order.customer.id),class:"admin_link" do %>
      <%= @order.customer.last_name %><%= @order.customer.first_name %>
        <% end %>
    </tr>
    <tr>
      <td>注文日</td>
      <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
    </tr>

      <td>配送先</td>
      <td>
        〒<%= @order.zip_code.to_s.insert(3, "-") %>
        <%= @order.address %></br>
        <%= @order.name %>
      </td>

    <tr>
      <td>支払方法</td>
      <td><%= @order.payment_method %></td>
    </tr>

    <tr class="order_status">
      <td>注文ステータス</td>

      <td valign="middle">
        <%= form_with model: @order, url: admin_order_path, local:true, method: :patch do |f| %>
          <%#= f.select :status, Order.statuses.keys.map {|k| [I18n.t("enums.order.status.#{k}"), k]} %>
          <%= f.select :status, Order.statuses.keys.map {|k| [k, k]} %>
          <%= f.submit "更新", class:"btn btn-success" %>
        <% end %>
      </td>

      </td>
    </tr>
  </tbody>
</table>

</div>

<div class="row mt-3">
  <div class="col-md-9 d-flex">
    <table class="table table-bordered border-dark table-hover align-middle custom-table">
      <thead>
        <tr align="center">
          <th scope="col" style="width: 30%">商品名</th>
          <th scope="col" style="width: 15%">単価(税込)</th>
          <th scope="col" style="width: 10%">数量</th>
          <th scope="col" style="width: 15%">小計</th>
          <th scope="col" style="width: 25%">製作ステータス</th>
        </tr>
      </thead>
      <tbody class="production_status">
         <% @order_items.each do |order_item| %>
         <tr valign="middle">
         <td align="center"><%= order_item.item.name %></td>
         <td align="center"><%= (order_item.price*1.1).floor.to_s(:delimited) %>円</td>
         <td align="center"><%= order_item.amount %></td>

         <td align="center">
         <%= (order_item.price * 1.1 * order_item.amount).to_i %>円</td>
         <td align="center">
        <%= form_with model: order_item, url: admin_order_detail_path(order_item.id), method: :patch do |f| %>
        <%= f.select :creating_status, OrderDetail.creating_statuses.keys.map { |s| [OrderDetail.human_attribute_name("status.#{s}"), s] } %>
         <%= f.submit "更新",class:"btn btn-sm" %>
         <% end %>
         <% end %>
         </td>

         </tr>

      </tbody>
    </table>
    </div>

  <div class="col-md-3">
    <table class="table">
      <tbody>
         <tr>
           <td><strong>商品合計</strong></td>
           <td align="right"><%= (@order.order_details.sum { |order_detail| order_detail.price * 1.1 * order_detail.amount }).floor.to_s(:delimited) %>円</td>
         </tr>

           <td><strong>送料</strong></td>
           <td align="right"><%= @order.postage.to_s(:billing_amount)%>円</td>
         </tr>

         <tr>
           <td><strong>請求金額合計</strong></td>
           <td align="right"><%= (@order.postage.to_i + @order.order_details.sum { |order_detail| order_detail.price * 1.1 * order_detail.amount }).floor.to_s(:delimited) %>円</td>
         </tr>
      </tbody>
      </table>
    </div>

    </div>
  </div>
</div>