config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root to: 'homes#top'
# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do
  root 'homes#top'
  resources :items, only: [:index, :new, :create, :show, :edit, :update]
  resources :genres, only: [:index, :create, :edit, :update,]
  resources :customers, only: [:index, :show, :edit, :update]
  resources :orders, only: [:show, :update]
  resources :order_details, only: [:update]
  # resource :genres, only: [:create, :edit]
end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  scope module: :public do
    root to: 'homes#top'
    get '/homes/about' => "homes#about"
    resources :items, only: [:index, :show]
    get'/customers/information'=>'customers#show'
    get'/customers/information/edit'=>'customers#edit'
    patch'/customers/information'=>'customers#update'
    get'/customers/check'=>'customers#check'
    patch'/customers/withdraw'=>'customers#withdraw'
    get '/customers/check'=>'customers#check'
    patch '/customers/withdraw'=>'customers#withdraw'
    #post '/items' => 'items#create'
    delete '/cart_items' => 'cart_items#all_destroy', as: 'all_destroy'
    patch 'cart_items' => 'cart_items#create'
    resources :cart_items, only:[:index, :update, :create, :destroy]
    resources :orders, only:[:new, :index, :show]
    post '/orders/confirm'=>'orders#confirm'
    get '/orders/thanks'=>'orders#thanks'
    post '/orders/complete'=>'orders#complete'
    resources :addresses, only:[:index, :edit, :create, :update, :destroy]
    resources :genres, only: [:show], as: "customers_genres", path: "customers/genres"
  end


end

app/models/address.rb
class Address < ApplicationRecord
 belongs_to :customer
 
  def zip_code_and_address_and_name
    "〒#{self.zip_code}  #{self.address}  #{self.name}"
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :cart_items
  has_many :orders

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :addresses
         
  def active_for_authentication?
    super && self.is_active?
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
 has_one_attached :image

 belongs_to :genre

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  enum status: { 入金待ち: 0, 入金確認: 1, 製作中:2, 発送準備中:3, 発送済み:4 }
  enum payment_method: { クレジットカード: 0, 銀行振込: 1 }
  # 入金待ち="0"、入金確認="1"、製作中="2"、発送準備中="3"、発送済み="4"

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  enum creating_status: {
      "着手不可" => 0,
      "製作待ち" => 1,
      "製作中" => 2,
      "製作完了" =>3,
  }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

def index
  @genres = Genre.all
end

def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to '/admin/genres'
end

def edit
  @genre = Genre.find(params[:id])
end

def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to '/admin/genres'
end

  def show
    @genres = Genre.all
    @genre = Genre.find(params[:id])
  end


  private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 #before_action :configure_permitted_parameters, if: :devise_controller?
before_action :authenticate_admin!, if: :admin_url
before_action :authenticate_customer!, if: :customer_url

   private
   def admin_url
     request.fullpath.starts_with?('/admin')
   end
   
   def customer_url
     request.fullpath.starts_with?('/cart_items')
   end

   def after_sign_in_path_for(resource)
     case resource
     when Admin
         admin_root_path
     when Customer
         root_path
     end
   end
   
  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :admin
       new_admin_session_path
    elsif resource_or_scope == :customer
       root_path
    end
  end

#   private
#   def configure_permitted_parameters
#     devise_parameter_sanitizer.permit(:sign_in, keys:[:email, :encrypted_password])
#     devise_parameter_sanitizer.permit(:sign_up, keys:[:email, :phone_number, :zip_code, :address, :first_name_kana, :last_name_kana, :first_name, :last_name])
#     devise_parameter_sanitizer.permit(:account_update, keys:[:email, :phone_number, :zip_code, :address, :first_name_kana, :last_name_kana, :first_name, :last_name])
#   end

 end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/admin_helper.rb
module Admin::AdminHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/admin/genres/edit.html.erb
<div class="container px-5 px-sm-0">
  <h4>ジャンル編集です</h4>
  <div class="row mt-4">
        <%= form_with model: @genre,url: admin_genre_path(@genre.id), method: :patch do |f| %>
          <table class="table table-borderless">
            <thead>
              <tr>
                <td>ジャンル名</td>
                <td><%= f.text_field :name %></td>
                <td><%= f.submit '変更を保存', class:'btn btn-success' %></td>
              </tr>
            </thead>
          </table>
        <% end %>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container px-5 px-sm-0">
  <h3>ジャンル一覧・追加</h3>
  <div class="row mt-3">
      <div class="col-md-5">
<!-- ジャンル新規登録フォーム -->
       <%= form_with model: Genre.new,url: admin_genres_path do |f| %>
          <table class="table table-borderless">
            <thead>
              <tr>
                <td>ジャンル名</td>
                <td><%= f.text_field :name %></td>
                <td><%= f.submit '新規登録', class:'btn btn-success' %></td>
              </tr>
            </thead>
          </table>
       <% end %>
      </div>
  </div>
<!--ジャンル一覧-->
  <div class="row mt-3">
    <div class="col-md-5">
      <table class="table table-inverse">
        <thead>
          <tr>
            <th class="pl-5">ジャンル名</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @genres.each do |genre| %>
            <tr>
              <td><%= genre.name %></td>
              <td><%= link_to edit_admin_genre_path(genre), class:"btn btn-success" do %>  編集する  </td>
            </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/genres/show.erb
<div class="container my-5">
  <div class="row">
    <div class="col-md-3">
      <table class="table text-center table-hover">
  <thead class="table-bordered">
    <tr>
      <th class="h4">ジャンル一覧</th>
    </tr>
  </thead>
  <% @genres.each do |genre| %>
  <tr>
    <td>
      <%= link_to admin_genre_path(genre.id), method: :get, class: "text-dark" do %>
      <%= genre.name %>
      <% end %>
    </td>
  </tr>
  <% end %>
</table>
    </div>

  <div class="col-md-9">
    <h3><strong><%= @genre.name %>一覧</strong></h3>
    <div class="d-flex flex-wrap">
      <% @genre.items.each do |item| %>
        <div class="col-3 mt-3">
          <%= link_to item_path(item), class: "text-dark" do %>
          <% if item.image.attached? %>
            <%= image_tag item.image, size: "180x140" %>
          <% else %>
            <!-- 画像が存在しない場合 -->
             <%= image_tag 'kabotya', size: "180x140" %>
           <% end %>
            <%= item.name %><br>
             ¥<%= item.non_taxed_price.to_s(:delimited) %>(税込)
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>