config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root to: 'homes#top'
# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do
  root 'homes#top'
  resources :items, only: [:index, :new, :create, :show, :edit, :update]
  resources :genres, only: [:index, :create, :edit, :update,]
  resources :customers, only: [:index, :show, :edit, :update]
  resources :orders, only: [:show, :update]
  resources :order_details, only: [:update]
  # resource :genres, only: [:create, :edit]
end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  scope module: :public do
    root to: 'homes#top'
    get '/homes/about' => "homes#about"
    resources :items, only: [:index, :show]
    get'/customers/information'=>'customers#show'
    get'/customers/information/edit'=>'customers#edit'
    patch'/customers/information'=>'customers#update'
    get'/customers/check'=>'customers#check'
    patch'/customers/withdraw'=>'customers#withdraw'
    get '/customers/check'=>'customers#check'
    patch '/customers/withdraw'=>'customers#withdraw'
    #post '/items' => 'items#create'
    delete '/cart_items' => 'cart_items#all_destroy', as: 'all_destroy'
    patch 'cart_items' => 'cart_items#create'
    resources :cart_items, only:[:index, :update, :create, :destroy]
    resources :orders, only:[:new, :index, :show]
    post '/orders/confirm'=>'orders#confirm'
    get '/orders/thanks'=>'orders#thanks'
    post '/orders/complete'=>'orders#complete'
    resources :addresses, only:[:index, :edit, :create, :update, :destroy]
    resources :genres, only: [:show], as: "customers_genres", path: "customers/genres"
  end


end

app/models/address.rb
class Address < ApplicationRecord
 belongs_to :customer
 
  def zip_code_and_address_and_name
    "〒#{self.zip_code}  #{self.address}  #{self.name}"
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :cart_items
  has_many :orders

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :addresses
         
  def active_for_authentication?
    super && self.is_active?
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
 has_one_attached :image

 belongs_to :genre

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  enum status: { 入金待ち: 0, 入金確認: 1, 製作中:2, 発送準備中:3, 発送済み:4 }
  enum payment_method: { クレジットカード: 0, 銀行振込: 1 }
  # 入金待ち="0"、入金確認="1"、製作中="2"、発送準備中="3"、発送済み="4"

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  enum creating_status: {
      "着手不可" => 0,
      "製作待ち" => 1,
      "製作中" => 2,
      "製作完了" =>3,
  }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 #before_action :configure_permitted_parameters, if: :devise_controller?
before_action :authenticate_admin!, if: :admin_url
before_action :authenticate_customer!, if: :customer_url

   private
   def admin_url
     request.fullpath.starts_with?('/admin')
   end
   
   def customer_url
     request.fullpath.starts_with?('/cart_items')
   end

   def after_sign_in_path_for(resource)
     case resource
     when Admin
         admin_root_path
     when Customer
         root_path
     end
   end
   
  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :admin
       new_admin_session_path
    elsif resource_or_scope == :customer
       root_path
    end
  end

#   private
#   def configure_permitted_parameters
#     devise_parameter_sanitizer.permit(:sign_in, keys:[:email, :encrypted_password])
#     devise_parameter_sanitizer.permit(:sign_up, keys:[:email, :phone_number, :zip_code, :address, :first_name_kana, :last_name_kana, :first_name, :last_name])
#     devise_parameter_sanitizer.permit(:account_update, keys:[:email, :phone_number, :zip_code, :address, :first_name_kana, :last_name_kana, :first_name, :last_name])
#   end

 end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_header_admin.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand" href="/"><%= image_tag 'cake.png', :size =>'100x100' %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <li>
            <%= link_to admin_items_path,class: 'nav-link text-dark' do %>
              商品一覧
            <% end %>
          </li>
          <li>
            <%= link_to admin_customers_path,class: 'nav-link text-dark' do %>
              会員一覧
            <% end %>
          </li>
          <li>
            <%= link_to admin_root_path,class: 'nav-link text-dark' do %>
              注文履歴一覧
            <% end %>
          </li>
          <li>
            <%= link_to admin_genres_path,class: 'nav-link text-dark' do %>
              ジャンル一覧
            <% end %>
          </li>
          <li>
            <%= link_to destroy_admin_session_path, method: :delete,class: 'nav-link text-dark' do %>
              ログアウト
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>

app/views/layouts/_header_customer.html.erb
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand" href="/"><%= image_tag 'cake.png', :size =>'100x100' %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <span class="welcome message for loged-in customer">
        ようこそ、<%= current_customer.last_name %>さん！
      </span>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <li>
            <div class="input-group">
              <input type="text" class="form-control" placeholder="商品検索">
                <span class="input-group-btn">
                  <button type="button" class="btn btn-primary">検索</button>
                </span>
              </div>
            </li>
          <li>
            <%= link_to customers_information_path,class: 'nav-link text-dark' do %>
              マイページ
            <% end %>
          </li>
          <li>
            <%= link_to items_path,class: 'nav-link text-dark' do %>
              商品一覧
            <% end %>
          </li>
          <li>
            <%= link_to cart_items_path,class: 'nav-link text-dark' do %>
              カート
            <% end %>
          </li>
          <li>
            <%= link_to destroy_customer_session_path, method: :delete,class: 'nav-link text-dark' do %>
              ログアウト
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>

app/views/layouts/_header_logout.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
      <a class="navbar-brand" href="/"><%= image_tag 'cake.png', :size =>'100x100' %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <li>
            <%= link_to homes_about_path,class: 'nav-link text-dark' do %>
              About
            <% end %>
          </li>
          <li>
            <%= link_to items_path,class: 'nav-link text-dark' do %>
              商品一覧
            <% end %>
          </li>
          <li>
            <%= link_to new_customer_registration_path ,class: 'nav-link text-dark' do %>
              新規登録
            <% end %>
          </li>
          <li>
            <%= link_to new_customer_session_path ,class: 'nav-link text-dark' do %>
              ログイン
            <% end %>
          </li>
        </ul>
      </div>
      </div>
  </nav>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NagnoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
        <% if customer_signed_in? %>
          <%= render 'layouts/header_customer' %>
        <% elsif admin_signed_in? %>
          <%= render 'layouts/header_admin' %>
        <% else %>
          <%= render 'layouts/header_logout' %>
        <% end %>
    </header>
    <%= yield %>
    <div>
      <%= flash[:success] %>
      <%= flash[:danger] %>
    </div>
  </body>
</html>